environment: development
debug: true
log_level: DEBUG

azure:
  subscription_id: "${AZURE_SUBSCRIPTION_ID}"
  tenant_id: "${AZURE_TENANT_ID}"
  client_id: "${AZURE_CLIENT_ID}"
  client_secret: "${AZURE_CLIENT_SECRET}"
  resource_group: "${AZURE_RESOURCE_GROUP}"
  log_analytics_workspace_id: "${AZURE_LOG_ANALYTICS_WORKSPACE_ID}"

kubernetes:
  kubeconfig_path: "${HOME}/.kube/config"
  namespace: "default"

discovery:
  cost_analysis_days: 30
  metrics_hours: 24
  include_recommendations: true
  include_detailed_metrics: true
  include_cost_allocation: true
  parallel_workers: 5
  timeout_seconds: 600

storage:
  backend: "file"
  base_path: "./phase1_discovery_data"

api:
  host: "localhost"
  port: 8000
  reload: true